function canTileBeReplaced(id, data) {}
var CONSTANT_REPLACEABLE_TILES = {};
CONSTANT_REPLACEABLE_TILES[0] = true;
CONSTANT_REPLACEABLE_TILES[8] = true;
CONSTANT_REPLACEABLE_TILES[9] = true;
CONSTANT_REPLACEABLE_TILES[10] = true;
CONSTANT_REPLACEABLE_TILES[11] = true;
CONSTANT_REPLACEABLE_TILES[31] = true;
CONSTANT_REPLACEABLE_TILES[51] = true;
CONSTANT_REPLACEABLE_TILES[78] = true;
CONSTANT_REPLACEABLE_TILES[106] = true;
