declare namespace Files {
    let of: (...paths: any) => java.io.File;
    let is: (pathOrFile: any) => boolean;
    let isFile: (pathOrFile: any) => boolean;
    let isFileOrNew: (pathOrFile: any) => boolean;
    let isDirectory: (pathOrFile: any) => boolean;
    let isDirectoryOrNew: (pathOrFile: any) => boolean;
    let isFileDirectory: (pathOrFile: any) => boolean;
    let isFileDirectoryOrNew: (pathOrFile: any) => boolean;
    let isHashingAlgorithm: (algorithm: any) => boolean;
    let basename: (pathOrFile: any, extension?: Nullable<string | boolean>) => string;
    let dirname: (pathOrFile: any) => Nullable<string>;
    let extension: (pathOrFile: any, extension?: Nullable<string>) => Nullable<string>;
    let join: (...paths: any) => Nullable<string>;
    let resolve: (pathOrFile: any, ...where: any) => Nullable<string>;
    let relative: (pathOrFile: any, directoryPathOrFile: any) => Nullable<string>;
    let ensureFile: (pathOrFile: any) => void;
    let ensureDirectory: (pathOrFile: any) => void;
    let ensureFileDirectory: (pathOrFile: any) => void;
    let walkUnsafe: (pathOrFile: any, callback: (file: java.io.File, relative: Nullable<string>) => void, filter?: "file" | "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string, reverseDirectories?: boolean) => void;
    let walk: (pathOrFile: any, callback: (file: java.io.File, relative: Nullable<string>) => void, filter?: "file" | "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string, reverseDirectories?: boolean) => Nullable<void>;
    let listUnsafe: (pathOrFile: any, mode?: "relative" | "name" | "nameWithoutExtension" | "relativeWithoutExtension" | "file", filter?: "file" | "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string, reverseDirectories?: boolean) => (string | java.io.File)[];
    let list: (pathOrFile: any, mode?: "relative" | "name" | "nameWithoutExtension" | "relativeWithoutExtension" | "file", filter?: "file" | "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string, reverseDirectories?: boolean) => Nullable<(string | java.io.File)[]>;
    let listFilesUnsafe: (pathOrFile: any, mode?: "relative" | "name" | "nameWithoutExtension" | "relativeWithoutExtension" | "file", extensions?: string | string[], filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => (string | java.io.File)[];
    let listFiles: (pathOrFile: any, mode?: "relative" | "name" | "nameWithoutExtension" | "relativeWithoutExtension" | "file", extensions?: string | string[], filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => Nullable<(string | java.io.File)[]>;
    let listDirectoriesUnsafe: (pathOrFile: any, mode?: "relative" | "name" | "file", filter?: "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string, reverseDirectories?: boolean) => (string | java.io.File)[];
    let listDirectories: (pathOrFile: any, mode?: "relative" | "name" | "file", filter?: "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string, reverseDirectories?: boolean) => Nullable<(string | java.io.File)[]>;
    let readUnsafe: (pathOrFile: any) => Nullable<string>;
    let read: (pathOrFile: any) => Nullable<string>;
    let readLineUnsafe: (pathOrFile: any, line: number) => Nullable<string>;
    let readLine: (pathOrFile: any, line: number) => Nullable<string>;
    let readAsLinesUnsafe: (pathOrFile: any, fromLine?: number, toLine?: number, limitLength?: number) => string[];
    let readAsLines: (pathOrFile: any, fromLine?: number, toLine?: number, limitLength?: number) => Nullable<string[]>;
    let readAsBytesUnsafe: (pathOrFile: any) => native.Array<number>;
    let readAsBytes: (pathOrFile: any) => Nullable<native.Array<number>>;
    let writeUnsafe: (pathOrFile: any, textOrBytes: any) => void;
    let write: (pathOrFile: any, textOrBytes: any) => Nullable<void>;
    let writeLinesUnsafe: (pathOrFile: any, lines: any[]) => void;
    let writeLines: (pathOrFile: any, lines: any[]) => Nullable<void>;
    let writeFromStreamUnsafe: (stream: java.io.InputStream, pathOrFile: any) => void;
    let writeFromStream: (stream: java.io.InputStream, pathOrFile: any) => Nullable<void>;
    let appendUnsafe: (pathOrFile: any, textOrBytes: any, newLine?: boolean | number) => void;
    let append: (pathOrFile: any, textOrBytes: any, newLine?: boolean | number) => Nullable<void>;
    let writeStreamToStream: (inputStream: java.io.InputStream, outputStream: java.io.OutputStream) => void;
    let removeUnsafe: (pathOrFile: any, filter?: "file" | "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => void;
    let remove: (pathOrFile: any, filter?: "file" | "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => Nullable<void>;
    let copyUnsafe: (fromPathOrFile: any, toPathOrFile: any, filter?: "file" | "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string, appendInstead?: boolean) => void;
    let copy: (fromPathOrFile: any, toPathOrFile: any, filter?: "file" | "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string, appendInstead?: boolean) => Nullable<void>;
    let digestUnsafe: (pathOrFile: any, algorithm?: "md5" | "sha-1" | "sha-256" | "sha-384" | "sha-512" | java.security.MessageDigest, filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => string;
    let digest: (pathOrFile: any, algorithm?: "md5" | "sha-1" | "sha-256" | "sha-384" | "sha-512" | java.security.MessageDigest, filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => Nullable<string>;
    let compareUnsafe: (leftPathOrFile: any, rightPathOrFile: any, algorithm?: "md5" | "sha-1" | "sha-256" | "sha-384" | "sha-512" | java.security.MessageDigest, filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => boolean;
    let compare: (leftPathOrFile: any, rightPathOrFile: any, algorithm?: "md5" | "sha-1" | "sha-256" | "sha-384" | "sha-512" | java.security.MessageDigest, filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => Nullable<boolean>;
    let putEntryToZipUnsafe: (zipOutputStream: java.util.zip.ZipOutputStream, pathOrFile: any, filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => void;
    let putEntryToZip: (zipOutputStream: java.util.zip.ZipOutputStream, pathOrFile: any, filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => Nullable<void>;
    let packAsZipUnsafe: (zipPathOrFile: any, pathOrFile: any, filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => void;
    let packAsZip: (zipPathOrFile: any, pathOrFile: any, filter?: "file" | ((file: java.io.File, relative: Nullable<string>) => boolean), maxDepth?: number | boolean, relativePath?: string) => Nullable<void>;
    let unpackZipUnsafe: (zipPathOrFile: any, toPathOrFile: any, filter?: "file" | "directory" | ((entry: java.util.zip.ZipEntry, relative: string) => boolean), appendInstead?: boolean) => void;
    let unpackZip: (zipPathOrFile: any, toPathOrFile: any, filter?: "file" | "directory" | ((file: java.io.File, relative: Nullable<string>) => boolean), appendInstead?: boolean) => Nullable<void>;
}
